const dropDownData = [
  "All Departments",
  "Alexa Skills",
  "Amazon Devices",
  "Amazon Fresh",
  "Amazon Pharmacy",
  "Amazon Warehouse",
  "Appliances",
  "Apps &Games",
  "Arts, Crafts & Sewing",
  "Audible Books &Originals",
  "Automotive Parts & Accessories",
  "Baby",
  "Beauty & Personal Care",
  "Books",
  "CDs & Vinyl",
  "Cell Phones & Accessories",
  "Computers",
  "Credit and Payment Cards",
  "Digital Music",
  "Electronics",
  "Garden & Outdoor",
  "Gift Cards",
  "Grocery  & Gourmet Food",
  "Handmade",
  "Luxury Stores",
  "Magazine Subscriptions",
  "Office ProductsPet Supplies",
  "Premium Beauty",
  "Prime Video",
  "Smart Home",
  "Software",
  "Sports & Outdoors",
  "Subscribe & Save",
  "sear",
];

export default { dropDownData };
